POST http://localhost:5050/api/users/register
Content-Type: application/json

{
  "lastname": "Tran Thu",
  "firstname": "Mai",
  "email": "mai@lethai.vn",
  "password": "201161"
}

###

POST http://localhost:5050/api/users/login
Content-Type: application/json

{
  "email": "thanh@lethai.vn",
  "password": "220461"
}

###

GET http://localhost:5050/api/users

###

POST http://localhost:5050/api/users
Content-Type: application/json

{
  "lastname": "Le Thai Minh",
  "firstname": "Nghia",
  "email": "nghia@lethai.vn",
  "password": "071086",
  "avatar": "abcd",
  "info": "1234",
  "status": "INACTIVE"
}

###

PUT http://localhost:5050/api/users/62b32f74a1db67b36c6d9a9a
Content-Type: application/json

{
  "lastname": "Le Thai",
  "firstname": "Thanh",
  "email": "thanh@lethai.vn",
  "password": "",
  "avatar": "thanh.png",
  "info": "Tel: 0989984858",
  "status": "ACTIVE"
}

###

DELETE http://localhost:5050/api/users/62b333ec41b6dec5ad682092

